#!/bin/bash

name=scenario-test


mkdir -p "$name"/step1
mkdir -p "$name"/step2
touch "$name"/finish.md
touch "$name"/index.json
touch "$name"/intro.md

touch "$name"/background.sh

touch "$name"/step1/text.md
touch "$name"/step1/verify.sh

touch "$name"/step2/text.md
touch "$name"/step2/verify.sh


cat > "$name"/step1/verify.sh <<EOF

#!/bin/bash
#
#
# Enter some stuff!

EOF


cat > "$name"/step2/verify.sh <<EOF

#!/bin/bash
#
#
# Enter some stuff!

EOF

cat > "$name"/index.json <<EOF

{
  "title": "##--ADD-A-TITTLE--##",
  "description": "##--ADD-A-DESC--##",
  "details": {
    "intro": {
      "text": "intro.md",
      "background": "background.sh"
    },
    "steps": [
      {
        "title": "#--ENTER--STEP--1--#",
        "text": "step1/text.md",
        "verify": "step1/verify.sh"
      },
      {
        "title": "#--Enter--STEP--2--#",
        "text": "step2/text.md",
        "verify": "step2/verify.sh"
      }
    ],
    "finish": {
      "text": "finish.md"
    }
  },
  "backend": {
    "imageid": "kubernetes-kubeadm-1node"
  }
}

EOF


cat   > "$name"/finish.md <<EOF
<br>

### WELL DONE !

You solved this challenge!

EOF



cat   > "$name"/intro.md <<EOF

<br>

### Namaste!

Are you ready? Let's go!
<img src="https://raw.githubusercontent.com/srjoeraj/srjoeraj-killercoda-scenarios/refs/heads/main/assets/logo.png" alt="drawing" width="200"  height="200"/>



EOF





