apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: assets
  name: assets
spec:
  containers:
  - image: httpd
    name: assets
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
